### ISSUE TITLE
--json option doesn't actually return json

### ISSUE THREAD

**Issue by forivall** [prantlf/minified-size#2]
it returns a `util.inspect` format, which is not parsable by json parsers (ie. using [`jq`](https://stedolan.github.io/jq/) or [`json`](https://npm.im/json))

```
» minified-size --json ./build/**.js|json
json: error: input is not JSON: Bad string at line 1, column 5:
        [ { file: 'build/index.js',
        ....^
```

**Comment by prantlf** [comment]
Thank you for reporting this! It was compatible only with [JSON5](https://json5.org) :-)

I [fixed](https://github.com/prantlf/minified-size/commit/003e0a4b3eef2d84f0afdbc30296a6262e6693cf) the problem in [v2.0.3](https://github.com/prantlf/minified-size/releases/tag/v2.0.3).

Instead of just passing the result to `console.log`, which only prettifies the output, I format the "real JSON" by `JSON.strnigify` now.
